[build]
  publish = "public"
  functions = "netlify/functions"

# /note SPA リダイレクト
[[redirects]]
  from = "/note/*"
  to = "/note/index.html"
  status = 200

# API リダイレクト
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# キャッチオール
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
